### ISSUE TITLE
TypeError: Cannot read property parent of undefined

### ISSUE THREAD

**Issue by ruandre** [jonkemp/gulp-inline-css#16]
I get the following error when I run gulp using `v2.0.0` of `gulp-inline-css`:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (.../node_modules/gulp-inline-css/node_modules/inline-css/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (.../node_modules/gulp-inline-css/node_modules/inline-css/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (.../node_modules/gulp-inline-css/node_modules/inline-css/node_modules/cheerio/lib/static.js:19:14)
    at module.exports (.../node_modules/gulp-inline-css/node_modules/inline-css/lib/inline-css.js:15:21)
    at inlineCssWithCb (.../node_modules/gulp-inline-css/node_modules/inline-css/index.js:21:19)
    at .../node_modules/gulp-inline-css/node_modules/inline-css/index.js:35:9
    at .../node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/index.js:28:9
    at callback (.../node_modules/gulp-inline-css/node_modules/inline-css/node_modules/extract-css/node_modules/batch/index.js:147:12)
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```
Yet everything works just fine if I use `v0.2.2` :confused:

**Comment by jonkemp** [comment]
Yeah, 2.0 switched away from Juice so bugs are expected. I'm still working on writing tests for all the new modules, so hopefully that will catch a lot of things. I will look into this. Thanks!

**Comment by jonkemp** [comment]
The `inline-css` module has been patched. If you want to try version 2.0 again, please delete your `node_modules` folder and run `npm install` again. Actually, you can just uninstall `inline-css` and reinstall it, but when you do, make sure it's version 1.0.2.

**Comment by Austin-Stephens** [comment]
Had same issue. Patch worked, task runs great now with no error.
