### ISSUE TITLE
Error running basic example

### ISSUE THREAD

**Issue by Dottenpixel** [jonkemp/gulp-inline-css#48]
My code: 
```
gulp.task('inline', function() {
  return gulp.src('./dist/email-template.html')
    .pipe(inlineCss({
    	applyStyleTags: true,
    	applyLinkTags: true,
    	removeStyleTags: true,
    	removeLinkTags: true
    }))
    .pipe(gulp.dest('dist/'));
});
```
`$ gulp inline` renders:
```
Unhandled rejection Error: Error: Unexpected } (line 10148, char 41)
    at module.exports (…/node_modules/inline-css/lib/inline-css.js:30:15)
    at …/node_modules/inline-css/lib/inlineContent.js:25:27
    at…/node_modules/extract-css/index.js:38:9
    at callback (…/node_modules/batch/index.js:147:12)
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

**Comment by jonkemp** [comment]
Tests are passing. I would suggest removing and re-installing node_modules and try again.
